// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWStructuredBuffer<float> Result;
Texture2D<float4> Camera;
Texture2D<float4> Sample;
int Size;

[numthreads(10,10,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
	Result[id.x * Size + id.y] = abs(Camera[id.xy].x - Sample[id.xy].x);
}